In [11]:
import torch
a=torch.tensor([[1,2,3],[5,6,7]]) # creates the 2d tensor
print(a)
print(type(a))
print(a.ndim)

tensor([[1, 2, 3],
        [5, 6, 7]])
<class 'torch.Tensor'>
2


In [13]:
# creating the 3d tensor
d=torch.tensor([[[3,5],
                 [0,2],
                 [1,9]]])
print(d)
print(d.ndim)

tensor([[[3, 5],
         [0, 2],
         [1, 9]]])
3


In [5]:
b=torch.arange(start=0,step=3,end=100) # arange the number from 0 to 100 with step size 3
print(b)
print(type(b))

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])
<class 'torch.Tensor'>


In [6]:
b=torch.zeros(3,3) # creates the tensor of size 3X3
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
c=torch.zeros_like(b) # creates the same tensor of given size b
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# accessing the values using slicing 
d

tensor([[[3, 5],
         [0, 2],
         [1, 9]]])

In [32]:
d[0,1]

tensor([0, 2])

In [30]:
d[:,:1]

tensor([[[3, 5]]])

In [34]:
a

tensor([[1, 2, 3],
        [5, 6, 7]])

In [40]:
a[:,:2]

tensor([[1, 2],
        [5, 6]])

In [50]:
a[1,0]

tensor(5)